#!/bin/bash
python ./code/main.py \
--username DZ20370001 \
--password n0sliwSD!@# \
--mail_user shanjw@lamda.nju.edu.cn \
--mail_pass n0sliwSD!@# \
--location 中国江苏省南京市栖霞区仙林大道 \
--force \
--mail_notify
